# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2319fa1e39f332e3be888fa8c3b94d72f6ea303f080a19e53b8e658fc1b2e201dd5f037f10316caba9a82ab0ab6d348f343f731f2b40bcf39d5e6e047556c571

test:
  secret_key_base: 62de558cd00ce7a837983cf757eff482f7eb8b2faba125076c29429ad81f9359f5619154c84f787cfea0f58166630c1d11ce627c5ba1d969c4197f4576fe572c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
